FROM node:22-alpine AS base
RUN apk add --no-cache ffmpeg
WORKDIR /app

COPY package.json ./
COPY shared/package.json ./shared/
COPY worker/package.json ./worker/

RUN npm install --workspace=worker --workspace=shared

COPY shared/ ./shared/
COPY tsconfig.base.json ./
COPY worker/ ./worker/

WORKDIR /app/worker
RUN npx prisma generate

CMD ["node", "dist/index.js"]
